### ISSUE TITLE
Enable Logfile

### ISSUE THREAD

**Issue by Jdiesel87** [MattMcManis/Glow#3]
Can you create the option to enable the creation of a logfile and set the destination?

log-file=path/to/logfile.txt

**Comment by MattMcManis** [comment]
What actions would you want the log file to record? Previous configurations?

**Comment by Jdiesel87** [comment]
Just enable the mpv logging in the mpv.conf file not enabling logging in your application. mpv will overwrite the logfile everytime new playback is started.

--log-file=<path>
Opens the given path for writing, and print log messages to it. Existing files will be truncated. The log level is at least -v -v, but can be raised via --msg-level (the option cannot lower it below the forced minimum log level).

**Comment by MattMcManis** [comment]
I will add it under the General tab and release an update soon.

**Comment by Jdiesel87** [comment]
Excellent! Thanks for this

**Comment by MattMcManis** [comment]
The program's update button no longer seems to work with GitHub servers when downloading the zip.
https://github.com/MattMcManis/Glow/releases/download/v0.0.5.4-alpha/Glow.zip

It's under the General Tab, after Window Title.
I tested it and ran a video, it produced log.txt file, all seems to work.

**Comment by MattMcManis** [comment]
The update problem should now also be solved in v0.0.5.5, due to a GitHub Security Protocol Type change.
https://github.com/MattMcManis/Glow/releases/download/v0.0.5.5-alpha/Glow.zip

How is it all working?

**Comment by Jdiesel87** [comment]
Seems to be working for me. I noticed that the app now requires admin privileges to run though.

**Comment by MattMcManis** [comment]
I had always made it Administrator by default so it could be placed in Program Files and update. Will it not run for Guest or Normal User?
