### ISSUE TITLE
Download version issue

### ISSUE THREAD

**Issue by mjuzikfrik** [MattMcManis/Glow#7]
Under the last release when I download zip archive I get 0.7.1 version instead of 0.7.2.

**Comment by MattMcManis** [comment]
Sorry for late reply, I have not checked this project in a while. I tried downloading and it gave 0.7.2, it may have been a caching issue. Does this problem still happen?

https://github.com/MattMcManis/Glow/releases/tag/v0.0.7.2-alpha

https://github.com/MattMcManis/Glow/releases/download/v0.0.7.2-alpha/Glow.zip

**Comment by mjuzikfrik** [comment]
No problem. Now it works as expected. :)
